# Generated by Django 4.2.16 on 2025-08-17 17:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubmittedDetail',
            fields=[
                ('pk_bint_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('dat_created', models.DateTimeField(auto_now_add=True)),
                ('json_details', models.JSONField()),
                ('fk_created', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('fk_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.customform')),
            ],
        ),
    ]
